export const speciesDetailStyles = {
    name:{
        mb:'3vh'
    },
    description:{
        fontSize:{
            
        }
    },
    wrap:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'space-between',
        padding:'3%',
        width:'100%'
    },
    imageSet:{
        height:{
            xs:'80vh',
            md:'60vh',
        },
        width:{
            xs:'100%',
            md:'40vw'
        },
        overflowY:'auto',
    },
    graph:{
        height:{
            xs:'80vh',
            md:'60vh',
        },
        width:{
            xs:'100%',
            md:'40vw'
        },
    },
    bigGraph:{
        height: '80vh',
        width:'95vw'
    },
    map:{
        display:'flex',
        justifyContent:'center'
    },
    classification:{
        height: '80vh',
        width:'95vw'
    }
  }